# Generated by Django 3.2.9 on 2021-11-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=15, unique=True)),
                ('level', models.CharField(max_length=2)),
                ('duration', models.CharField(max_length=2)),
                ('departmentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.department')),
            ],
        ),
    ]
