# Generated by Django 3.1.3 on 2021-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='departmentname',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursename',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.SmallIntegerField(choices=[(6, '6'), (8, '8')], default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=25),
        ),
    ]
