# Generated by Django 3.1.3 on 2021-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=30, null=True)),
                ('room_no', models.CharField(blank=True, max_length=15, null=True)),
                ('capacity', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(blank=True, choices=[('AC', 'AC'), ('NON AC', 'NON AC')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=25, null=True)),
                ('floor', models.CharField(blank=True, choices=[(1, '1'), (2, '2')], max_length=10, null=True)),
                ('block', models.CharField(blank=True, choices=[('AIDED', 'AIDED'), ('SELF', 'SELF')], max_length=10, null=True)),
            ],
        ),
    ]
