# Generated by Django 3.2.9 on 2021-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
