# Generated by Django 3.2.9 on 2021-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
