# Generated by Django 3.2.9 on 2021-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_rename_event_eventss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_on', models.DateField(blank=True, null=True)),
                ('booked_from', models.DateField(blank=True, null=True)),
                ('booked_to', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.eventss')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.room')),
            ],
        ),
    ]
