# Generated by Django 3.1.3 on 2021-12-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20211208_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventss',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='event_name',
            new_name='event',
        ),
    ]
