# Generated by Django 3.2.9 on 2021-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20211209_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_name',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')]),
        ),
    ]
