# Generated by Django 3.2.9 on 2021-12-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20211209_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.event')),
            ],
        ),
    ]
