# Generated by Django 3.2.9 on 2022-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20211209_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images'),
        ),
    ]
