# Generated by Django 3.2.9 on 2022-02-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0019_classroom_classroomteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomteachers',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
