# Generated by Django 3.2.9 on 2022-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_classroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
